name: fe-dev
on:
  push:
    branches: ["main"]
jobs:
  # main 브랜치에서 push가 이루어지면 아래 작업들이 이루어짐
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn vite build
