name: fe-dev
on:
  push:
    branches: ["main"]
jobs:
  # main 브랜치에서 push가 이루어지면 아래 작업들이 이루어짐
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn vite build

      - name: Deploy # Deploy to EC2
        run: aws deploy create-deployment
          --application-name irumu
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name irumuwish-webservice-group
          --s3-location bucket=irumu,key=build-fe.zip,bundleType=zip
