name: fe-dev
on:
  push:
    branches: ["main"]
jobs:
  # main 브랜치에서 push가 이루어지면 아래 작업들이 이루어짐
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn vite build

      - name: S3 Deploy
        run: aws s3 sync ./dist s3://irumu
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
